### ISSUE TITLE
The result seems not right

### ISSUE THREAD

**Issue by huangkeju** [gimme1dollar/reweighted_random-walks_graph-matching#1]
Hi, thanks for providing this code! I try to use this code for graph matching but the result does not seem right. When I run your exmaple the result also seems weird, as shown in the following. I'm new to graph matching and I have no idea if anything goes wrong. Any help is appreciated!

(pytorch12) E:\Gits\reweighted-randomwalks-graph-matching-main>python main.py
Exp with inlier 2 & outier 1
accuracy: [[0.]]         score: [[3.50628403]]

(pytorch12) E:\Gits\reweighted-randomwalks-graph-matching-main>python main.py
Exp with inlier 2 & outier 1
accuracy: [[0.5]]        score: [[1.98697515]]

(pytorch12) E:\Gits\reweighted-randomwalks-graph-matching-main>python main.py
Exp with inlier 30 & outier 1
accuracy: [[0.66666667]]         score: [[1386.46806292]]

(pytorch12) E:\Gits\reweighted-randomwalks-graph-matching-main>python main.py
Exp with inlier 30 & outier 1
accuracy: [[0.56666667]]         score: [[1294.53522896]]

(pytorch12) E:\Gits\reweighted-randomwalks-graph-matching-main>python main.py
Exp with inlier 30 & outier 1
accuracy: [[0.53333333]]         score: [[1264.06076764]]

**Comment by gimme1dollar** [comment]
What is wrong with the result? It seems quite right to me. With more in-liers, the probability of getting an accurate result goes higher with a better score. Please let me know if I am wrong.
